<?php

require_once 'dbh.inc.php';
require_once 'login_model.inc.php';

if ($_SERVER['REQUEST_METHOD'] === "POST") {
    $email = $_POST['email'];
    
    $recaptcha_secret = "6LcvqEwqAAAAAH8sDF1KJDGzZScSlZQpocnR_gxX"; // THIS ONE GENERATED BY GOOGLE AND IT IS CALLED SECRET KEY. 
    $recaptcha_response = $_POST['g-recaptcha-response']; //G-recaptcha response is the users click to the checkbox this rely on T/F I think.


    $verify_response = file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret=' . $recaptcha_secret . '&response=' . $recaptcha_response); //Verifying your RESPONSE with SECRET KEY.
        $response_data = json_decode($verify_response); //json_decode means it is formatting using JSON

    if ($response_data->success) {  // If RESPONSE IS TRUE or SUCCESS the Login will be executed from Query.
        echo "reCAPTCHA verified successfully!";
        get_user($pdo, $email);
        echo "Login Confirmed";
    } else {
            // reCAPTCHA validation failed, means unsuccessful recaptcha.
            echo "reCAPTCHA verification failed. Please try again.";
    }

} else {
    // If not a POST request, redirect to the login page
    header("Location: ../login.php");
    exit();
}